version: '3.8'
services:
  studentapi:
    build:
      context: ./StudentApi
    ports:
      - "8080:8080"
    
  studentweb:
    build:
      context: ./StudentWeb
    ports:
      - "8081:8080"
    depends_on:
      - studentapi